# category_rules.py
# YTÜ mevzuat kategori kuralları ve anahtar kelimeler.

CATEGORY_RULES = {'mazeret_sinavi': {'files': ['DD-007'],
                    'keywords': ['mazeret',
                                 'mazeret sınavı',
                                 'mazeret sinavi',
                                 'rapor',
                                 'sağlık raporu',
                                 'saglik raporu',
                                 'hastalık',
                                 'hastalik',
                                 'sınava giremedim',
                                 'sinava giremedim',
                                 'sınava girememek',
                                 'sinava girememek',
                                 'trafik kazası',
                                 'trafik kazasi',
                                 'doğal afet',
                                 'dogal afet',
                                 'ölüm belgesi',
                                 'olum belgesi',
                                 'raporu teslim',
                                 'mazeret dilekçesi',
                                 'mazeret dilekcesi']},
 'mezuniyet_sinavi': {'files': ['DD-015'],
                      'keywords': ['mezuniyet sınavı',
                                   'mezuniyet sinavi',
                                   'mezuniyet sınavına girmek',
                                   'mezuniyet sinavina girmek',
                                   'en fazla iki ders',
                                   'iki dersim kaldı',
                                   'iki dersim kaldi',
                                   'son iki ders',
                                   'mezuniyet sınav başvurusu',
                                   'mezuniyet sinav basvurusu',
                                   'mezuniyet sınav hakkı',
                                   'mezuniyet sinav hakki']},
 'bitirme_calismasi': {'files': ['DD-022'],
                       'keywords': ['bitirme',
                                    'bitirme çalışması',
                                    'bitirme calismasi',
                                    'bitirme projesi',
                                    'tez',
                                    'bitirme danışmanı',
                                    'bitirme danismani',
                                    'bitirme konusu',
                                    'bitirme sınavı',
                                    'bitirme sinavi',
                                    'bitirme sunumu',
                                    'bitirme tezi']},
 'not_donusumu': {'files': ['DD-039', 'YTU_Not_Donusumu'],
                  'keywords': ['not dönüşümü',
                               'not donusumu',
                               "100'lük",
                               '100lük',
                               '100 luk',
                               'yüzlük',
                               'yuzluk',
                               "4'lük",
                               '4lük',
                               '4 luk',
                               'agno kaç puan',
                               'agno kac puan',
                               'agno karşılığı',
                               'agno karsiligi',
                               'agno 100',
                               'ortalama 100',
                               'notum kaça denk gelir',
                               'notum kaca denk gelir']},
 'yuzde_on': {'files': ['DD-040'],
              'keywords': ['yüzde on',
                           'yuzde on',
                           '%10',
                           'ilk yüzde on',
                           'ilk yuzde on',
                           'yüzde 10',
                           'yuzde 10',
                           'ikinci öğretim',
                           'ikinci ogretim',
                           'harç indirimi',
                           'harc indirimi',
                           'öğrenim ücreti',
                           'ogrenim ucreti',
                           'katkı payı',
                           'katki payi',
                           'yüzde on sıralaması',
                           'yuzde on siralamasi']},
 'sinav_itiraz': {'files': ['DD-042'],
                  'keywords': ['sınav sonucuna itiraz',
                               'sinav sonucuna itiraz',
                               'nota itiraz',
                               'not itirazı',
                               'not itirazi',
                               'sınav kağıdı inceleme',
                               'sinav kagidi inceleme',
                               'maddi hata',
                               'itiraz süresi',
                               'itiraz suresi',
                               'komisyon',
                               'not değişikliği',
                               'not degisikligi',
                               'final notuma itiraz',
                               'bütünleme notuma itiraz',
                               'butunleme notuma itiraz']},
 'ders_kayit': {'files': ['DD-125'],
                'keywords': ['ders kayıt',
                             'ders kayit',
                             'ders seçimi',
                             'ders secimi',
                             'ders ekleme',
                             'ders silme',
                             'ekle sil',
                             'üstten ders',
                             'ustten ders',
                             'üst yarıyıldan ders',
                             'ust yariyildan ders',
                             'alttan ders',
                             'kredi sınırı',
                             'kredi siniri',
                             'ders alma',
                             'ders kontenjan',
                             'ders grubu',
                             'çakışma',
                             'cakisma',
                             'ders çakışması',
                             'ders cakismasi',
                             'üst dönem',
                             'ust donem']},
 'yaz_okulu': {'files': ['YÖ-007', 'YÖ-007'],
               'keywords': ['yaz okulu',
                            'yaz öğretimi',
                            'yaz ogretimi',
                            'yazın ders',
                            'yazin ders',
                            'başka üniversiteden ders',
                            'baska universiteden ders',
                            'yaz okulu süresi',
                            'yaz okulu suresi',
                            'yaz okulunda ders alma',
                            'yaz okulunda kredi',
                            'yaz okulu final',
                            'yaz okulu ücreti',
                            'yaz okulu ucreti']},
 'ozel_ogrenci_ytuye_gelen': {'files': ['YO-014_Ozel_Ogrenci_01_YTUye_Gelen',
                                        'YÖ-014_Ozel_Ogrenci_01_YTUye_Gelen',
                                        'Ozel_Ogrenci_01_YTUye_Gelen',
                                        'YTÜye_Gelen',
                                        'YTUye_Gelen'],
                              'keywords': ["başka üniversiteden ytü'ye özel öğrenci",
                                           "baska universiteden ytu'ye ozel ogrenci",
                                           'başka üniversiteden ytüye özel öğrenci',
                                           'baska universiteden ytuye ozel ogrenci',
                                           'diğer yükseköğretim kurumu öğrencisi',
                                           'diger yuksekogretim kurumu ogrencisi',
                                           "ytü'den ders almak isteyen özel öğrenci",
                                           'ytuden ders almak isteyen ozel ogrenci',
                                           'ytüden ders almak isteyen özel öğrenci',
                                           'ytuden ders almak isteyen ozel ogrenci',
                                           "ytü'de özel öğrenci",
                                           'ytude ozel ogrenci',
                                           'ytüde özel öğrenci',
                                           'ytude ozel ogrenci',
                                           'üniversitemizden ders almak',
                                           'universitemizden ders almak',
                                           "ytü'den ders alma",
                                           'ytuden ders alma',
                                           'ytüden ders alma',
                                           'ytuden ders alma',
                                           "başka okuldan ytü'ye ders",
                                           'baska okuldan ytuye ders',
                                           'başka üniversite öğrencisi ytü',
                                           'baska universite ogrencisi ytu',
                                           'özel öğrenci kabul',
                                           'ozel ogrenci kabul',
                                           'özel öğrenci olarak ytü',
                                           'ozel ogrenci olarak ytu']},
 'ozel_ogrenci_ytuden_giden': {'files': ['YO-014_Ozel_Ogrenci_02_YTUden_Giden',
                                         'YÖ-014_Ozel_Ogrenci_02_YTUden_Giden',
                                         'Ozel_Ogrenci_02_YTUden_Giden',
                                         'YTUden_Giden'],
                               'keywords': ['ytü öğrencisi başka üniversiteden ders',
                                            'ytu ogrencisi baska universiteden ders',
                                            'ytü öğrencilerinin diğer yükseköğretim kurumlarına başvurusu',
                                            'ytu ogrencilerinin diger yuksekogretim kurumlarina basvurusu',
                                            'üniversitemiz öğrencilerinin diğer yükseköğretim kurumlarına',
                                            'universitemiz ogrencilerinin diger yuksekogretim kurumlarina',
                                            'başka üniversiteden ders alma',
                                            'baska universiteden ders alma',
                                            'başka üniversitede ders',
                                            'baska universitede ders',
                                            'diğer yükseköğretim kurumundan ders',
                                            'diger yuksekogretim kurumundan ders',
                                            'özel öğrenci olarak başka üniversiteden',
                                            'ozel ogrenci olarak baska universiteden',
                                            "ytü'den başka üniversiteye özel öğrenci",
                                            'ytuden baska universiteye ozel ogrenci',
                                            'ytüden başka üniversiteye özel öğrenci',
                                            'ytuden baska universiteye ozel ogrenci',
                                            'özel öğrenci intibak',
                                            'ozel ogrenci intibak',
                                            '30 yerel kredi',
                                            'otuz yerel kredi',
                                            'özel öğrencilikte geçirdiği süre',
                                            'ozel ogrencilikte gecirdigi sure']},
 'akademik_danismanlik': {'files': ['YÖ-031', 'YÖ-031'],
                          'keywords': ['danışman',
                                       'danisman',
                                       'akademik danışman',
                                       'akademik danisman',
                                       'danışman onayı',
                                       'danisman onayi',
                                       'danışman ne yapar',
                                       'danisman ne yapar',
                                       'öğrenci danışmanlığı',
                                       'ogrenci danismanligi',
                                       'ders onayı',
                                       'ders onayi',
                                       'danışman görevi',
                                       'danisman gorevi',
                                       'danışman ataması',
                                       'danisman atamasi']},
 'onceki_ogrenme': {'files': ['YÖ-064', 'YÖ-064'],
                    'keywords': ['önceki öğrenme',
                                 'onceki ogrenme',
                                 'önceden kazanılmış',
                                 'onceden kazanilmis',
                                 'muafiyet sınavı',
                                 'muafiyet sinavi',
                                 'sertifika saydırma',
                                 'sertifika saydirma',
                                 'kredilendirme',
                                 'ders muafiyeti',
                                 'muaf olma']},
 'sinav_yonergesi': {'files': ['YÖ-075', 'YÖ-075'],
                     'keywords': ['sınav',
                                  'sinav',
                                  'vize',
                                  'ara sınav',
                                  'ara sinav',
                                  'final',
                                  'bütünleme',
                                  'butunleme',
                                  'quiz',
                                  'kısa sınav',
                                  'kisa sinav',
                                  'ödev',
                                  'odev',
                                  'proje',
                                  'sınav kuralları',
                                  'sinav kurallari',
                                  'sınav süresi',
                                  'sinav suresi',
                                  'sınav programı',
                                  'sinav programi',
                                  'başarı notu',
                                  'basari notu',
                                  'ders değerlendirme',
                                  'ders degerlendirme']},
 'isletmede_mesleki_egitim': {'files': ['YÖ-088', 'YÖ-088'],
                              'keywords': ['işletmede mesleki eğitim',
                                           'isletmede mesleki egitim',
                                           'ime',
                                           'mesleki eğitim',
                                           'mesleki egitim',
                                           'işletme eğitimi',
                                           'isletme egitimi',
                                           'uygulamalı eğitim',
                                           'uygulamali egitim',
                                           'işletme protokolü',
                                           'isletme protokolu',
                                           'eğitici personel',
                                           'egitici personel',
                                           'haftalık rapor',
                                           'haftalik rapor',
                                           'aylık rapor',
                                           'aylik rapor',
                                           'işletme dosyası',
                                           'isletme dosyasi']},
 'azami_sure': {'files': ['YÖ-096', 'YÖ-096'],
                'keywords': ['azami süre',
                             'azami sure',
                             'azami öğrenim',
                             'azami ogrenim',
                             'ek süre',
                             'ek sure',
                             'ek sınav',
                             'ek sinav',
                             'sınırsız sınav',
                             'sinirsiz sinav',
                             'kayıt silme',
                             'kayit silme',
                             'ilişik kesilme',
                             'ilisik kesilme',
                             'başarısız ders',
                             'basarisiz ders',
                             'öğrenim süresi doldu',
                             'ogrenim suresi doldu']},
 'esdegerlik_intibak': {'files': ['YÖ-097', 'YÖ-097'],
                        'keywords': ['eşdeğerlik',
                                     'esdegerlik',
                                     'intibak',
                                     'ders saydırma',
                                     'ders saydirma',
                                     'muafiyet',
                                     'yatay geçiş ders saydırma',
                                     'yatay gecis ders saydirma',
                                     'dikey geçiş ders saydırma',
                                     'dikey gecis ders saydirma',
                                     'transkript',
                                     'başarılı ders',
                                     'basarili ders',
                                     'derslerin sayılması',
                                     'derslerin sayilmasi',
                                     'yarıyıl intibakı',
                                     'yariyil intibaki']},
 'lisansustu_genel_basvuru': {'files': ['YTU_Lisansustu_01_Genel_Basvuru', 'Lisansustu_01_Genel_Basvuru'],
                              'keywords': ['lisansüstü başvuru',
                                           'lisansustu basvuru',
                                           'yüksek lisans başvuru',
                                           'yuksek lisans basvuru',
                                           'lisansüstü kabul',
                                           'lisansustu kabul',
                                           'ales',
                                           'yabancı dil',
                                           'yabanci dil',
                                           'lisans mezunu olmak',
                                           'başvuru ve değerlendirme',
                                           'basvuru ve degerlendirme',
                                           'ales puanı',
                                           'ales puani',
                                           'ales şartı',
                                           'ales sarti',
                                           'yüksek lisans ales',
                                           'yuksek lisans ales',
                                           'tezsiz yüksek lisans ales',
                                           'tezsiz yuksek lisans ales',
                                           'lisansüstü programına başvurmak',
                                           'lisansustu programina basvurmak']},
 'lisansustu_tezli_yuksek_lisans': {'files': ['YTU_Lisansustu_02_Tezli_Yuksek_Lisans', 'Lisansustu_02_Tezli_Yuksek_Lisans'],
                                    'keywords': ['tezli yüksek lisans',
                                                 'tezli yuksek lisans',
                                                 'yüksek lisans tezi',
                                                 'yuksek lisans tezi',
                                                 'tezli yüksek lisans süresi',
                                                 'tezli yuksek lisans suresi',
                                                 'tezli yüksek lisans akts',
                                                 'tezli yuksek lisans akts',
                                                 'tezli yüksek lisans kredi',
                                                 'tezli yuksek lisans kredi',
                                                 'seminer dersi',
                                                 'araştırma yöntemleri ve bilimsel etik',
                                                 'arastirma yontemleri ve bilimsel etik',
                                                 'tez danışmanı',
                                                 'tez danismani',
                                                 'yüksek lisans tez savunması',
                                                 'yuksek lisans tez savunmasi',
                                                 'tezli yüksek lisans diploması',
                                                 'tezli yuksek lisans diplomasi',
                                                 'tez ve uzmanlık alan dersi',
                                                 'tez ve uzmanlik alan dersi']},
 'lisansustu_tezsiz_yuksek_lisans': {'files': ['YTU_Lisansustu_03_Tezsiz_Yuksek_Lisans', 'Lisansustu_03_Tezsiz_Yuksek_Lisans'],
                                     'keywords': ['tezsiz yüksek lisans',
                                                  'tezsiz yuksek lisans',
                                                  'dönem projesi',
                                                  'donem projesi',
                                                  'tezsiz yüksek lisans süresi',
                                                  'tezsiz yuksek lisans suresi',
                                                  'tezsiz yüksek lisans kredi',
                                                  'tezsiz yuksek lisans kredi',
                                                  'tezsiz yüksek lisans akts',
                                                  'tezsiz yuksek lisans akts',
                                                  'tezsiz yüksek lisans diploması',
                                                  'tezsiz yuksek lisans diplomasi',
                                                  'tezsizden tezliye geçiş',
                                                  'tezsizden tezliye gecis',
                                                  'tezli programa geçiş',
                                                  'tezli programa gecis',
                                                  'yeterlik sınavı uygulanıp uygulanmayacağı',
                                                  'yeterlik sinavi uygulanip uygulanmayacagi']},
 'lisansustu_doktora': {'files': ['YTU_Lisansustu_04_Doktora', 'Lisansustu_04_Doktora'],
                        'keywords': ['doktora',
                                     'doktora programı',
                                     'doktora programi',
                                     'doktora başvuru',
                                     'doktora basvuru',
                                     'doktora ales',
                                     'doktora yabancı dil',
                                     'doktora yabanci dil',
                                     'lisans derecesiyle doktora',
                                     'lisans derecesi ile doktora',
                                     'doktora süresi',
                                     'doktora suresi',
                                     'doktora yeterlik',
                                     'yeterlik sınavı',
                                     'yeterlik sinavi',
                                     'tez izleme komitesi',
                                     'tez önerisi',
                                     'tez onerisi',
                                     'doktora tez savunması',
                                     'doktora tez savunmasi',
                                     'doktora diploması',
                                     'doktora diplomasi']},
 'lisansustu_sanatta_yeterlik': {'files': ['YTU_Lisansustu_05_Sanatta_Yeterlik', 'Lisansustu_05_Sanatta_Yeterlik'],
                                 'keywords': ['sanatta yeterlik',
                                              'sanatta yeterlik programı',
                                              'sanatta yeterlik programi',
                                              'sanatta yeterlik başvuru',
                                              'sanatta yeterlik basvuru',
                                              'sanatta yeterlik süresi',
                                              'sanatta yeterlik suresi',
                                              'sanatta yeterlik ales',
                                              'sanatta yeterlik yabancı dil',
                                              'sanatta yeterlik yabanci dil',
                                              'portfolyo',
                                              'resital',
                                              'konser',
                                              'temsil',
                                              'sanatta yeterlik diploması',
                                              'sanatta yeterlik diplomasi']},
 'lisansustu_bilimsel_hazirlik_kayit_ogretim': {'files': ['YTU_Lisansustu_06_Bilimsel_Hazirlik_Kayit_Ogretim', 'Lisansustu_06_Bilimsel_Hazirlik_Kayit_Ogretim'],
                                                'keywords': ['bilimsel hazırlık',
                                                             'bilimsel hazirlik',
                                                             'lisansüstü özel öğrenci',
                                                             'lisansustu ozel ogrenci',
                                                             'lisansüstü yatay geçiş',
                                                             'lisansustu yatay gecis',
                                                             'lisansüstü kayıt',
                                                             'lisansustu kayit',
                                                             'öğretim planı',
                                                             'ogretim plani',
                                                             'lisansüstü ders açılması',
                                                             'lisansustu ders acilmasi',
                                                             'lisansüstü not sistemi',
                                                             'lisansustu not sistemi',
                                                             'ders başarı notu',
                                                             'ders basari notu',
                                                             'aa ba bb cb cc dc dd fd ff',
                                                             'akademik başarı not ortalaması',
                                                             'akademik basari not ortalamasi',
                                                             'kayıt yenileme',
                                                             'kayit yenileme',
                                                             'izinli sayılma',
                                                             'izinli sayilma',
                                                             'disiplin',
                                                             'tebligat']},
 'cap': {'files': ['YÖ-098_CAP', 'YÖ-098_CAP'],
         'keywords': ['çap',
                      'cap',
                      'çift anadal',
                      'cift anadal',
                      'çift ana dal',
                      'cift ana dal',
                      'çift anadal programı',
                      'cift anadal programi',
                      'double major',
                      'ikinci anadal',
                      'ikinci ana dal',
                      'çap başvuru',
                      'cap basvuru',
                      'çap koşul',
                      'cap kosul',
                      'çap agno',
                      'cap agno',
                      'çap kontenjan',
                      'cap kontenjan',
                      'çap devam',
                      'cap devam',
                      'çap mezuniyet',
                      'cap mezuniyet',
                      'çap kaydı',
                      'cap kaydi',
                      'çap programı',
                      'cap programi',
                      'çap için ortalama',
                      'cap icin ortalama',
                      'çap başvuru şartı',
                      'cap basvuru sarti',
                      'çift anadal başvuru',
                      'cift anadal basvuru',
                      'çift anadal devam',
                      'cift anadal devam',
                      'çift anadal mezuniyet',
                      'cift anadal mezuniyet']},
 'yandal': {'files': ['YÖ-098_YANDAL', 'YÖ-098_YANDAL'],
            'keywords': ['yan dal',
                         'yandal',
                         'minor',
                         'yan dal programı',
                         'yan dal programi',
                         'yandal programı',
                         'yandal programi',
                         'yan dal sertifikası',
                         'yan dal sertifikasi',
                         'yandal sertifikası',
                         'yandal sertifikasi',
                         'yandal başvuru',
                         'yandal basvuru',
                         'yan dal başvuru',
                         'yan dal basvuru',
                         'yandal koşul',
                         'yandal kosul',
                         'yan dal koşul',
                         'yan dal kosul',
                         'yandal devam',
                         'yan dal devam',
                         'yandal mezuniyet',
                         'yan dal mezuniyet',
                         'yan dal dersi',
                         'yandal dersi',
                         'yan dal kredi',
                         'yandal kredi',
                         'yan dal süresi',
                         'yan dal suresi',
                         'yan dal kaydı',
                         'yan dal kaydi',
                         'yandal kaydı',
                         'yandal kaydi',
                         'yan dal programından ayrılma',
                         'yan dal programindan ayrilma',
                         'yandaldan ayrılma',
                         'yandaldan ayrilma']},
 'kurum_ici_yatay_gecis': {'files': ['YÖ-098_KURUM_ICI_YATAY_GECIS', 'YÖ-098_KURUM_ICI_YATAY_GECIS'],
                           'keywords': ['kurum içi yatay geçiş',
                                        'kurum ici yatay gecis',
                                        'üniversite içinde yatay geçiş',
                                        'universite icinde yatay gecis',
                                        'ytü içinde yatay geçiş',
                                        'ytu icinde yatay gecis',
                                        'ytü içinde bölüm değiştirmek',
                                        'ytu icinde bolum degistirmek',
                                        'ytü içinde başka bölüme geçmek',
                                        'ytu icinde baska bolume gecmek',
                                        'kendi üniversitemde bölüm değiştirmek',
                                        'kendi universitemde bolum degistirmek',
                                        'kendi okulumda bölüm değiştirmek',
                                        'kendi okulumda bolum degistirmek',
                                        'başka bölüme geçmek istiyorum',
                                        'baska bolume gecmek istiyorum',
                                        'bölüm değiştirmek',
                                        'bolum degistirmek']},
 'kurumlar_arasi_yatay_gecis': {'files': ['YÖ-098_KURUMLAR_ARASI_YATAY_GECIS', 'YÖ-098_KURUMLAR_ARASI_YATAY_GECIS'],
                                'keywords': ['kurumlar arası yatay geçiş',
                                             'kurumlar arasi yatay gecis',
                                             "başka üniversiteden ytü'ye geçiş",
                                             "baska universiteden ytu'ye gecis",
                                             'başka üniversiteden ytüye geçiş',
                                             'baska universiteden ytuye gecis',
                                             'başka üniversiteden yatay geçiş',
                                             'baska universiteden yatay gecis',
                                             "farklı üniversiteden ytü'ye geçmek",
                                             "farkli universiteden ytu'ye gecmek",
                                             'farklı üniversiteden ytüye geçmek',
                                             'farkli universiteden ytuye gecmek',
                                             'başka okuldan yatay geçiş',
                                             'baska okuldan yatay gecis',
                                             'başka okuldan ytüye geçiş',
                                             'baska okuldan ytuye gecis',
                                             'ikinci öğretimden yatay geçiş',
                                             'ikinci ogretimden yatay gecis']},
 'staj': {'files': ['YÖ-103', 'YÖ-103'],
          'keywords': ['staj',
                       'zorunlu staj',
                       'staj süresi',
                       'staj suresi',
                       'staj başvurusu',
                       'staj basvurusu',
                       'staj defteri',
                       'staj dosyası',
                       'staj dosyasi',
                       'staj komisyonu',
                       'staj kabul',
                       'iş günü',
                       'is gunu',
                       'staj raporu',
                       'staj değerlendirme',
                       'staj degerlendirme',
                       'mezuniyet için staj',
                       'mezuniyet icin staj']},
 'merkezi_yerlestirme_yatay_gecis': {'files': ['YÖ-098_MERKEZI_YERLESTIRME_YATAY_GECIS', 'YÖ-098_MERKEZI_YERLESTIRME_YATAY_GECIS'],
                                     'keywords': ['merkezi yerleştirme',
                                                  'merkezi yerlestirme',
                                                  'merkezi yerleştirme puanı',
                                                  'merkezi yerlestirme puani',
                                                  'merkezi puan',
                                                  'merkezi puanım',
                                                  'merkezi puanim',
                                                  'ek madde 1',
                                                  'ek madde-1',
                                                  'myp',
                                                  'myp ile geçiş',
                                                  'myp ile gecis',
                                                  'myp ile yatay geçiş',
                                                  'myp ile yatay gecis',
                                                  'ösym puanımla geçiş',
                                                  'osym puanimla gecis',
                                                  'yerleştiğim yılki puan',
                                                  'yerlestigim yilki puan',
                                                  'taban puanım yetiyor',
                                                  'taban puanim yetiyor',
                                                  'taban puanla geçiş',
                                                  'taban puanla gecis',
                                                  'yerleştirme puanıyla yatay geçiş',
                                                  'yerlestirme puaniyla yatay gecis']},
 'yurt_disi_yatay_gecis': {'files': ['YÖ-098_YURT_DISI_YATAY_GECIS', 'YÖ-098_YURT_DISI_YATAY_GECIS'],
                           'keywords': ['yurt dışından yatay geçiş',
                                        'yurt disindan yatay gecis',
                                        'yurtdışından yatay geçiş',
                                        'yurtdisindan yatay gecis',
                                        'yurt dışı üniversiteden geçiş',
                                        'yurt disi universiteden gecis',
                                        'yurtdışı üniversiteden geçiş',
                                        'yurtdisi universiteden gecis',
                                        "yabancı üniversiteden ytü'ye geçiş",
                                        "yabanci universiteden ytu'ye gecis",
                                        'yabancı üniversiteden ytüye geçiş',
                                        'yabanci universiteden ytuye gecis',
                                        'yurtdışı üniversiteden ytüye geçmek',
                                        'yurtdisi universiteden ytuye gecmek']},
 'dikey_gecis': {'files': ['YÖ-098_DIKEY_GECIS', 'YÖ-098_DIKEY_GECIS'],
                 'keywords': ['dikey geçiş',
                              'dikey gecis',
                              'dgs',
                              'dgs ile geçiş',
                              'dgs ile gecis',
                              'ön lisanstan lisansa geçiş',
                              'on lisanstan lisansa gecis',
                              'meslek yüksekokulundan lisansa geçiş',
                              'meslek yuksekokulundan lisansa gecis']},
 'yatay_gecis_genel': {'files': ['YÖ-098_YATAY_GECIS', 'YÖ-098_YATAY_GECIS'],
                       'keywords': ['yatay geçiş', 'yatay gecis', 'geçiş başvurusu', 'gecis basvurusu', 'geçiş hakkı', 'gecis hakki']},
 'lisansustu_kontenjan_danismanlik_ek_sure': {'files': ['YTU_Lisansustu_07_Kontenjan_Danismanlik_Ek_Sure', 'Lisansustu_07_Kontenjan_Danismanlik_Ek_Sure'],
                                              'keywords': ['lisansüstü kontenjan',
                                                           'lisansustu kontenjan',
                                                           'kontenjan',
                                                           'danışman başına',
                                                           'danisman basina',
                                                           'tez danışmanlığı en fazla',
                                                           'tez danismanligi en fazla',
                                                           'öğretim üyesi başına',
                                                           'ogretim uyesi basina',
                                                           'on dört',
                                                           'on dort',
                                                           '14 öğrenci',
                                                           '14 ogrenci',
                                                           'on altı',
                                                           'on alti',
                                                           '16 öğrenci',
                                                           '16 ogrenci',
                                                           'üniversite-sanayi',
                                                           'universite sanayi',
                                                           'kontenjan yüzde elli',
                                                           'kontenjan %50',
                                                           'yüzde 50 artırılabilir',
                                                           'yuzde 50 artirilabilir',
                                                           'afet',
                                                           'salgın',
                                                           'salgin',
                                                           'ek süre',
                                                           'ek sure',
                                                           'azami süreden sayılmaz',
                                                           'azami sureden sayilmaz',
                                                           'aynı anda birden fazla lisansüstü',
                                                           'ayni anda birden fazla lisansustu',
                                                           'tezsiz hariç aynı anda',
                                                           'tezsiz haric ayni anda',
                                                           'seminer dersi',
                                                           'seminer tanımı',
                                                           'seminer tanimi',
                                                           'tezine yönelik konu',
                                                           'tezine yonelik konu',
                                                           'öğretim planı',
                                                           'ogretim plani',
                                                           'lisansüstü not sistemi',
                                                           'lisansustu not sistemi']},
 'diploma_bilgileri': {'files': ['YO-119_Diploma_01_Diploma_Bilgileri', 'YÖ-119_Diploma_01_Diploma_Bilgileri', 'Diploma_01_Diploma_Bilgileri'],
                       'keywords': ['diploma dili',
                                    'diploma türkçe ingilizce',
                                    'diploma turkce ingilizce',
                                    'diploma boyutu',
                                    'diploma ölçü',
                                    'diploma olcu',
                                    '365mm',
                                    '280mm',
                                    '232mm',
                                    '317mm',
                                    'diplomada yer alan bilgiler',
                                    'diploma ön yüz',
                                    'diploma on yuz',
                                    'diploma arka yüz',
                                    'diploma arka yuz',
                                    'diploma numarası',
                                    'diploma numarasi',
                                    'ikinci öğretim ibaresi',
                                    'ikinci ogretim ibaresi',
                                    'çap ibaresi',
                                    'cap ibaresi',
                                    'çift anadal ibaresi',
                                    'cift anadal ibaresi',
                                    'mavi mürekkep',
                                    'mavi murekkep',
                                    'diplomayı kim imzalar',
                                    'diplomayi kim imzalar',
                                    'rektör imzası',
                                    'rektor imzasi',
                                    'dekan müdür imzası',
                                    'dekan mudur imzasi',
                                    'lisans diploması',
                                    'lisans diplomasi',
                                    'ön lisans diploması',
                                    'on lisans diplomasi',
                                    'yüksek lisans diploması',
                                    'yuksek lisans diplomasi']},
 'diploma_mezuniyet_tarihleri': {'files': ['YO-119_Diploma_02_Mezuniyet_Tarihleri', 'YÖ-119_Diploma_02_Mezuniyet_Tarihleri', 'Diploma_02_Mezuniyet_Tarihleri'],
                                 'keywords': ['mezuniyet tarihi',
                                              'lisans mezuniyet tarihi',
                                              'ön lisans mezuniyet tarihi',
                                              'on lisans mezuniyet tarihi',
                                              'tezsiz yüksek lisans mezuniyet tarihi',
                                              'tezsiz yuksek lisans mezuniyet tarihi',
                                              'tezli lisansüstü mezuniyet tarihi',
                                              'tezli lisansustu mezuniyet tarihi',
                                              'doktora mezuniyet tarihi',
                                              'yönetim kurulu toplantı tarihi',
                                              'yonetim kurulu toplanti tarihi',
                                              'enstitü yönetim kurulu toplantı tarihi',
                                              'nihai nüsha enstitüye teslim',
                                              'nihai nusha enstituye teslim',
                                              'tezin teslim edildiği tarih',
                                              'tezin teslim edildigi tarih']},
 'diploma_eki_yandal_belgeler': {'files': ['YO-119_Diploma_03_Diploma_Eki_Yandal_Belgeler',
                                           'YÖ-119_Diploma_03_Diploma_Eki_Yandal_Belgeler',
                                           'Diploma_03_Diploma_Eki_Yandal_Belgeler'],
                                 'keywords': ['diploma eki',
                                              'diploma eki ingilizce',
                                              'diploma eki dili',
                                              'diploma supplement',
                                              'yan dal sertifikası',
                                              'yan dal sertifikasi',
                                              'yandal sertifikası',
                                              'yandal sertifikasi',
                                              'yan dal sertifikası ortalama',
                                              'yan dal sertifikasi ortalama',
                                              '2.5 ortalama',
                                              'diploma yerine geçmez',
                                              'diploma yerine gecmez',
                                              'geçici mezuniyet belgesi',
                                              'gecici mezuniyet belgesi',
                                              'çıkış belgesi',
                                              'cikis belgesi',
                                              '1982',
                                              'mezun belgesi',
                                              'diplomam hazır değil',
                                              'diplomam hazir degil',
                                              'not durum belgesi',
                                              'mezuniyet transkripti',
                                              'staj durumu transkript',
                                              'transkript staj',
                                              'derece belgesi',
                                              'kayıt silme belgesi',
                                              'kayit silme belgesi']},
 'diploma_teslim_kayip_ikinci_nusha': {'files': ['YO-119_Diploma_04_Teslim_Kayip_Ikinci_Nusha',
                                                 'YÖ-119_Diploma_04_Teslim_Kayip_Ikinci_Nusha',
                                                 'Diploma_04_Teslim_Kayip_Ikinci_Nusha'],
                                       'keywords': ['diploma teslim',
                                                    'diploma teslimi',
                                                    '25 iş günü',
                                                    '25 is gunu',
                                                    'diploma sorgulama',
                                                    'noter vekalet',
                                                    'posta yolu',
                                                    'e-posta ile gönderilmez',
                                                    'kayıp diploma',
                                                    'kayip diploma',
                                                    'diplomamı kaybettim',
                                                    'diplomami kaybettim',
                                                    'ikinci nüsha',
                                                    'ikinci nusha',
                                                    'diploma yerine geçerli belge',
                                                    'diploma yerine gecerli belge',
                                                    'gazete ilanı',
                                                    'gazete ilani',
                                                    'diploma eki kaybı',
                                                    'diploma eki kaybi',
                                                    'yan dal sertifikası kaybı',
                                                    'yan dal sertifikasi kaybi',
                                                    'nüfus kaydı değişikliği',
                                                    'nufus kaydi degisikligi',
                                                    'ad soyad değişikliği',
                                                    'ad soyad degisikligi',
                                                    'hatalı diploma',
                                                    'hatali diploma',
                                                    'ücret',
                                                    'ucret',
                                                    'belge ücreti',
                                                    'belge ucreti']}}

YATAY_GECIS_CATEGORIES = ['kurum_ici_yatay_gecis',
 'kurumlar_arasi_yatay_gecis',
 'merkezi_yerlestirme_yatay_gecis',
 'yurt_disi_yatay_gecis',
 'dikey_gecis',
 'yatay_gecis_genel']


# V4 ek anahtar kelimeler:
# Buradaki amaç category_rules sözlüğünü baştan yazmadan, problemli kategorilerde
# öğrenci dilinde gelebilecek bazı ek ifadeleri mevcut keyword listelerine eklemek.
V4_EXTRA_KEYWORDS = {
    "diploma_bilgileri": [
        "diploma ebat", "diploma ölçüsü", "diploma olcusu", "diploma ön yüz", "diploma on yuz",
        "diploma arka yüz", "diploma arka yuz", "diploma numarası", "diploma numarasi",
        "yöksis bildirimi", "yoksis bildirimi", "mezuniyet bilgilerinin yöksise bildirilmesi",
        "çap ibaresi diplomada", "cap ibaresi diplomada", "ikinci öğretim ibaresi diplomada",
        "ikinci ogretim ibaresi diplomada"
    ],
    "diploma_mezuniyet_tarihleri": [
        "ön lisans mezuniyet tarihi", "on lisans mezuniyet tarihi",
        "lisans mezuniyet tarihi", "tezsiz yüksek lisans mezuniyet tarihi",
        "tezsiz yuksek lisans mezuniyet tarihi", "tezli lisansüstü mezuniyet tarihi",
        "tezli lisansustu mezuniyet tarihi", "tez teslim tarihi"
    ],
    "diploma_eki_yandal_belgeler": [
        "not durum belgesinde staj", "transkriptte staj", "diploma eki dili",
        "yandal sertifikası diploma yerine geçer mi", "yandal sertifikasi diploma yerine gecer mi",
        "geçici mezuniyet belgesi", "gecici mezuniyet belgesi"
    ],
    "diploma_teslim_kayip_ikinci_nusha": [
        "2005 sonrası kayıp diploma", "2005 sonrasi kayip diploma",
        "diploma ikinci nüsha", "diploma ikinci nusha", "diploma posta ile gönderilir mi",
        "diploma e-posta ile gönderilir mi", "diploma vekalet"
    ],
    "mazeret_sinavi": [
        "birinci derece yakın vefatı", "birinci derece yakin vefati",
        "yakının acil hastalığı", "yakinin acil hastaligi",
        "kaza zaptı", "kaza zapti", "kaza tespit tutanağı", "kaza tespit tutanagi",
        "istanbul ulaşım", "istanbul ulasim", "basın yayın duyurusu", "basin yayin duyurusu",
        "gözaltı", "gozalti", "tutukluluk", "çap anadal sınav çakışması", "cap anadal sinav cakismasi",
        "raporlu olduğu gün sınava girerse", "raporlu oldugu gun sinava girerse"
    ],
    "ozel_ogrenci_ytuye_gelen": [
        "başka üniversite öğrencisi ytüden ders almak", "baska universite ogrencisi ytuden ders almak",
        "ytüye gelen özel öğrenci agno", "ytuye gelen ozel ogrenci agno",
        "ytüden ders almak isteyen dış öğrenci", "ytuden ders almak isteyen dis ogrenci"
    ],
    "ozel_ogrenci_ytuden_giden": [
        "ytü öğrencisi başka üniversiteden ders almak istiyorum",
        "ytu ogrencisi baska universiteden ders almak istiyorum",
        "ytü öğrencisinin başka üniversiteden ders alması",
        "ytu ogrencisinin baska universiteden ders almasi",
        "30 yerel kredi özel öğrenci", "30 yerel kredi ozel ogrenci"
    ],
    "azami_sure": [
        "hiç alınmayan ders başarısız", "hic alinmayan ders basarisiz",
        "iki ek sınav hakkı", "iki ek sinav hakki",
        "sınırsız sınav hakkı", "sinirsiz sinav hakki",
        "ön koşul muafiyeti", "on kosul muafiyeti",
        "uygulamalı ders tanımı", "uygulamali ders tanimi"
    ],
    "staj": [
        "staj iki parçaya bölünür mü", "staj iki parcaya bolunur mu",
        "resmi tatil stajdan sayılır mı", "resmi tatil stajdan sayilir mi",
        "yaz okulunda staj", "sınav günü staj", "sinav gunu staj",
        "staj komisyonu en az kaç kişi", "staj komisyonu en az kac kisi"
    ],
    "ders_kayit": [
        "çap yandal 31 kredi", "cap yandal 31 kredi",
        "çakışan ders fakülte yönetim kurulu", "cakisan ders fakulte yonetim kurulu",
        "laboratuvar devam zorunluluğu", "laboratuvar devam zorunlulugu"
    ],
    "sinav_itiraz": [
        "itiraz başvuru süresi üç iş günü", "itiraz basvuru suresi uc is gunu",
        "sonuçlandırma süresi on iş günü", "sonuclandirma suresi on is gunu",
        "bütünlemeden üç iş günü önce", "butunlemeden uc is gunu once"
    ],
    "lisansustu_genel_basvuru": [
        "doktora mezunu aday ales yerine", "ales yerine hangi aralıkta puan",
        "ales yerine 55 75", "doktora mezunu ales muafiyeti"
    ],
    "lisansustu_kontenjan_danismanlik_ek_sure": [
        "danışman başına en fazla 14 öğrenci", "danisman basina en fazla 14 ogrenci",
        "tezsiz yüksek lisans en fazla 16 öğrenci", "tezsiz yuksek lisans en fazla 16 ogrenci",
        "afet salgın tez aşaması ek süre", "afet salgin tez asamasi ek sure"
    ],
}

for _category, _keywords in V4_EXTRA_KEYWORDS.items():
    if _category in CATEGORY_RULES:
        CATEGORY_RULES[_category].setdefault("keywords", [])
        for _keyword in _keywords:
            if _keyword not in CATEGORY_RULES[_category]["keywords"]:
                CATEGORY_RULES[_category]["keywords"].append(_keyword)


# V6 ekleri:
# İşletmede Mesleki Eğitim yönergesi 5 ayrı Word dosyasına bölündüğü için
# her dosyanın ayrı kategoriye düşmesini sağlayan file-key ve keyword ekleri.
# Uzun file-key'ler ingest sırasında önce denendiği için genel "YÖ-088" kuralından önce bu alt kategoriler yakalanır.
IME_V6_CATEGORY_RULES = {
    "isletmede_mesleki_egitim_tanimlar": {
        "files": [
            "YÖ-088_IME_01_Amac_Kapsam_Tanimlar",
            "YO-088_IME_01_Amac_Kapsam_Tanimlar",
            "IME_01_Amac_Kapsam_Tanimlar",
        ],
        "keywords": [
            "işletmede mesleki eğitim amacı", "isletmede mesleki egitim amaci",
            "işletmede mesleki eğitim kapsamı", "isletmede mesleki egitim kapsami",
            "bölüm komisyonu tanımı", "bolum komisyonu tanimi",
            "fakülte komisyonu tanımı", "fakulte komisyonu tanimi",
            "eğitici personel tanımı", "egitici personel tanimi",
            "sorumlu öğretim elemanı tanımı", "sorumlu ogretim elemani tanimi",
            "uygulamalı eğitim dosyası tanımı", "uygulamali egitim dosyasi tanimi",
        ],
    },
    "isletmede_mesleki_egitim_komisyonlar_gorevler": {
        "files": [
            "YÖ-088_IME_02_Koordinatorluk_Komisyonlar_Gorevler",
            "YO-088_IME_02_Koordinatorluk_Komisyonlar_Gorevler",
            "IME_02_Koordinatorluk_Komisyonlar_Gorevler",
        ],
        "keywords": [
            "koordinatörlük görevleri", "koordinatorluk gorevleri",
            "koordinatörün görevleri", "koordinatorun gorevleri",
            "fakülte komisyonunun görevleri", "fakulte komisyonunun gorevleri",
            "bölüm komisyonunun görevleri", "bolum komisyonunun gorevleri",
            "fakülte temsilcisinin görevleri", "fakulte temsilcisinin gorevleri",
            "bölüm temsilcisinin görevleri", "bolum temsilcisinin gorevleri",
            "dekanın görevleri", "dekanin gorevleri",
            "bölüm başkanının görevleri", "bolum baskaninin gorevleri",
            "bilgi bankası", "bilgi bankasi",
            "oryantasyon eğitimi", "oryantasyon egitimi",
            "iyileştirme talepleri", "iyilestirme talepleri",
            "işletme listelerini onaylamak", "isletme listelerini onaylamak",
            "protokol taslakları", "protokol taslaklari",
            "işletme eşleştirmesi", "isletme eslestirmesi",
        ],
    },
    "isletmede_mesleki_egitim_isletme_egitici_sorumlu_ogrenci": {
        "files": [
            "YÖ-088_IME_03_Isletme_Egitici_Sorumlu_Ogrenci_Gorevleri",
            "YO-088_IME_03_Isletme_Egitici_Sorumlu_Ogrenci_Gorevleri",
            "IME_03_Isletme_Egitici_Sorumlu_Ogrenci_Gorevleri",
        ],
        "keywords": [
            "sorumlu öğretim elemanının görevleri", "sorumlu ogretim elemaninin gorevleri",
            "işletme yöneticisinin görevleri", "isletme yoneticisinin gorevleri",
            "eğitici personelin görevleri", "egitici personelin gorevleri",
            "öğrencinin görev ve sorumlulukları", "ogrencinin gorev ve sorumluluklari",
            "haftalık çalışma planı", "haftalik calisma plani",
            "haftalık aylık çalışma raporu", "haftalik aylik calisma raporu",
            "uygulamalı eğitim dosyası", "uygulamali egitim dosyasi",
            "işletme değerlendirme formu", "isletme degerlendirme formu",
            "izin formu", "devamsızlık", "devamsizlik",
            "sendika faaliyetleri",
        ],
    },
    "isletmede_mesleki_egitim_basvuru_degerlendirme_itiraz": {
        "files": [
            "YÖ-088_IME_04_Ders_Sure_Basvuru_Degerlendirme_Itiraz",
            "YO-088_IME_04_Ders_Sure_Basvuru_Degerlendirme_Itiraz",
            "IME_04_Ders_Sure_Basvuru_Degerlendirme_Itiraz",
        ],
        "keywords": [
            "işletmede mesleki eğitim dersi", "isletmede mesleki egitim dersi",
            "işletmede mesleki eğitim süresi", "isletmede mesleki egitim suresi",
            "işletmede mesleki eğitim başvurusu", "isletmede mesleki egitim basvurusu",
            "başvuru ve tercih formu", "basvuru ve tercih formu",
            "agno en az 2.5", "agno en az 2,5",
            "7. yarıyıl", "7. yariyil",
            "alttan dersi bulunmamak", "alttan dersi bulunmamasi",
            "firma eşleştirilmesi", "firma eslestirilmesi",
            "asgari beş öğrenci", "asgari bes ogrenci",
            "15 akts", "30 akts",
            "değerlendirme sonuçlarına itiraz", "degerlendirme sonuclarina itiraz",
            "üç iş günü içinde itiraz", "uc is gunu icinde itiraz",
            "beş iş günü içinde karar", "bes is gunu icinde karar",
            "başarısız sayılır", "basarisiz sayilir",
        ],
    },
    "isletmede_mesleki_egitim_diger_hukumler": {
        "files": [
            "YÖ-088_IME_05_Diger_Hukumler_Staj_Saglik_Sigorta_Ucret_Gece",
            "YO-088_IME_05_Diger_Hukumler_Staj_Saglik_Sigorta_Ucret_Gece",
            "IME_05_Diger_Hukumler_Staj_Saglik_Sigorta_Ucret_Gece",
        ],
        "keywords": [
            "zorunlu stajlardan muaf", "zorunlu stajdan muaf",
            "başka bir yükseköğretim kurumunda işletmede mesleki eğitim", "baska bir yuksekogretim kurumunda isletmede mesleki egitim",
            "iş sağlığı ve güvenliği eğitimi", "is sagligi ve guvenligi egitimi",
            "iş güvenliği eğitimi", "is guvenligi egitimi",
            "sigorta hastalık kaza", "sigorta hastalik kaza",
            "sağlık raporu üç iş günü", "saglik raporu uc is gunu",
            "öğrenciye ödenecek ücret", "ogrenciye odenecek ucret",
            "üniversite tarafından ödeme yapılmaz", "universite tarafindan odeme yapilmaz",
            "gece çalışması", "gece calismasi",
            "gece çalışmalarına katılamaz", "gece calismalarina katilamaz",
            "ekle-sil haftası", "ekle sil haftasi",
            "mücbir mazeret", "mucbir mazeret",
        ],
    },
}

CATEGORY_RULES.update(IME_V6_CATEGORY_RULES)

# V6'da genel IME kategorisi de kalır; fakat yeni dosyalar uzun file-key ile alt kategorilere düşer.
# Soru tespitinde bu liste, "isletmede_mesleki_egitim" ana başlığını alt kategorilerle birlikte ele almak için kullanılır.
ISLETMEDE_MESLEKI_EGITIM_CATEGORIES = [
    "isletmede_mesleki_egitim",
    "isletmede_mesleki_egitim_tanimlar",
    "isletmede_mesleki_egitim_komisyonlar_gorevler",
    "isletmede_mesleki_egitim_isletme_egitici_sorumlu_ogrenci",
    "isletmede_mesleki_egitim_basvuru_degerlendirme_itiraz",
    "isletmede_mesleki_egitim_diger_hukumler",
]


# V7 ek anahtar kelimeler:
# Bu ekler, V6 testlerinde zayıf kalan yatay geçiş, özel öğrenci, IME, ders kayıt ve lisansüstü/bitirme ayrımı için eklendi.
# Sözlüğü baştan yazmak yerine mevcut kategori listelerini genişletiyoruz.
V7_EXTRA_KEYWORDS = {
    "kurum_ici_yatay_gecis": [
        "tek program", "sadece bir program", "yalnız bir program", "yalniz bir program",
        "aynı anda iki programa", "ayni anda iki programa",
        "özel yetenek", "ozel yetenek", "yetenek sınavı", "yetenek sinavi",
        "ytü içinde yatay geçiş", "ytu icinde yatay gecis",
    ],
    "kurumlar_arasi_yatay_gecis": [
        "ikinci öğretim", "ikinci ogretim", "açıköğretim", "acikogretim",
        "uzaktan öğretim", "uzaktan ogretim", "sınavsız ikinci üniversite", "sinavsiz ikinci universite",
        "başarı şartını sağlayamayan", "basari sartini saglayamayan",
        "türkiye bursları", "turkiye burslari",
    ],
    "merkezi_yerlestirme_yatay_gecis": [
        "bir kez yararlanılır", "bir kez yararlanilir", "sadece bir kez",
        "ek madde 1", "ek madde-1", "myp",
        "yerleştiği yılki puan", "yerlestigi yilki puan",
        "taban puanına eşit", "taban puanina esit",
        "önceki programına dönebilir", "onceki programina donebilir",
    ],
    "yatay_gecis_genel": [
        "geri dönebilir", "geri donebilir", "yatay geçişte tek program", "yatay geciste tek program",
    ],
    "ders_kayit": [
        "31 kredi", "otuz bir kredi", "28 kredi", "25 yerel kredi",
        "çakışan ders", "cakisan ders", "ilk iki hafta", "ders silme",
        "uygulamalı ders", "uygulamali ders", "laboratuvar devam",
        "ingilizce programda türkçe ders", "ingilizce programda turkce ders", "f0",
    ],
    "ozel_ogrenci_ytuden_giden": [
        "ytü öğrencisi başka üniversiteden ders", "ytu ogrencisi baska universiteden ders",
        "başka üniversiteden özel öğrenci olarak ders almak", "baska universiteden ozel ogrenci olarak ders almak",
        "diğer yükseköğretim kurumundan ders", "diger yuksekogretim kurumundan ders",
        "toplam 30 yerel kredi", "öğrencilik hakları devam eder", "ogrencilik haklari devam eder",
    ],
    "isletmede_mesleki_egitim_komisyonlar_gorevler": [
        "bölüm komisyonu kimlerden oluşur", "bolum komisyonu kimlerden olusur",
        "fakülte komisyonu kimlerden oluşur", "fakulte komisyonu kimlerden olusur",
        "oryantasyon", "bilgi bankası", "bilgi bankasi",
        "iyileştirme talepleri", "iyilestirme talepleri",
    ],
    "isletmede_mesleki_egitim_isletme_egitici_sorumlu_ogrenci": [
        "işletmedeki öğrenciden kim sorumlu", "isletmedeki ogrenciden kim sorumlu",
        "eğitici personel", "egitici personel",
        "işletme yöneticisi", "isletme yoneticisi",
        "sorumlu öğretim elemanı", "sorumlu ogretim elemani",
        "haftalık çalışma raporu", "haftalik calisma raporu",
    ],
    "isletmede_mesleki_egitim_basvuru_degerlendirme_itiraz": [
        "bir yarıyıl", "bir yariyil", "tam zamanlı", "tam zamanli", "kesintisiz",
        "agno 2.5", "agno 2,5", "15 akts", "30 akts", "%40", "%60",
        "değerlendirme sonucuna itiraz", "degerlendirme sonucuna itiraz",
    ],
    "isletmede_mesleki_egitim_diger_hukumler": [
        "iş güvenliği", "is guvenligi", "sigorta", "ücret", "ucret",
        "gece çalışması", "gece calismasi", "stajdan muaf",
    ],
    "lisansustu_tezli_yuksek_lisans": [
        "tezli yüksek lisans", "tezli yuksek lisans", "yüksek lisans tezi", "yuksek lisans tezi",
        "tez danışmanı", "tez danismani", "tez savunması", "tez savunmasi",
        "tez ve uzmanlık alan dersi", "tez ve uzmanlik alan dersi",
    ],
    "bitirme_calismasi": [
        "lisans bitirme", "bitirme jürisi", "bitirme jurisi",
    ],
    "azami_sure": [
        "iki ek sınav", "iki ek sinav", "sınırsız sınav", "sinirsiz sinav",
        "üç yarıyıl ek süre", "uc yariyil ek sure", "dört yarıyıl ek süre", "dort yariyil ek sure",
        "ön koşul", "on kosul", "başarısız ders sayısı", "basarisiz ders sayisi",
    ],
}

for _category, _keywords in V7_EXTRA_KEYWORDS.items():
    if _category in CATEGORY_RULES:
        CATEGORY_RULES[_category].setdefault("keywords", [])
        for _keyword in _keywords:
            if _keyword not in CATEGORY_RULES[_category]["keywords"]:
                CATEGORY_RULES[_category]["keywords"].append(_keyword)

# Tek başına "tez" çok genel olduğu için bitirme kategorisinde zayıflatıyoruz.
# Tezli yüksek lisans soruları artık scoring tarafında lisansüstü kategorisine daha güçlü gider.
if "bitirme_calismasi" in CATEGORY_RULES:
    CATEGORY_RULES["bitirme_calismasi"]["keywords"] = [
        _kw for _kw in CATEGORY_RULES["bitirme_calismasi"].get("keywords", [])
        if _kw not in ["tez"]
    ]


# =========================================================
# V8 EXTRA KEYWORDS
# V7'de genel başarı yükseldi; V8'de ise kalan problemli alanlara
# daha hedefli anahtar kelimeler ekliyoruz.
# Bu bölüm mevcut kuralları bozmaz, sadece ilgili kategori listelerini genişletir.
# =========================================================

V8_EXTRA_KEYWORDS = {
    "onceki_ogrenme": [
        "önceki öğrenmenin tanınması", "onceki ogrenmenin taninmasi",
        "tanıma başvurusu", "tanima basvurusu",
        "önceden kazanılmış yeterlilik", "onceden kazanilmis yeterlilik",
        "hizmet içi eğitim", "hizmet ici egitim",
        "iş yeri deneyimi", "is yeri deneyimi",
        "portfolyo", "sertifika", "18 kredi", "on sekiz kredi",
        "üç iş günü itiraz", "uc is gunu itiraz",
        "komisyon iki yıl", "komisyon iki yil",
        "başarısız dersler değerlendirilmez", "basarisiz dersler degerlendirilmez",
    ],
    "staj": [
        "zorunlu staj tamamlanmadan mezun olunamaz",
        "staj en fazla iki parçaya bölünebilir", "staj en fazla iki parcaya bolunebilir",
        "isteğe bağlı staj", "istege bagli staj",
        "staj komisyonu", "en az üç öğretim elemanı", "en az uc ogretim elemani",
        "staj sigorta girişi", "staj sigorta girisi",
        "sigorta girişi yapılmadan staja başlanamaz", "sigorta girisi yapilmadan staja baslanamaz",
        "staj defteri düzeltme", "staj defteri duzeltme",
        "staj reddine itiraz", "staj ret itiraz",
        "staj belgeleri ilk yarıyıl", "staj belgeleri ilk yariyil",
        "yaz okulunda staj", "haftada en az üç iş günü", "haftada en az uc is gunu",
    ],
    "mazeret_sinavi": [
        "belge bölüm başkanlığına teslim", "belge bolum baskanligina teslim",
        "özel muayenehane raporu", "ozel muayenehane raporu",
        "birinci derece yakın", "birinci derece yakin",
        "süre aşımı", "sure asimi",
        "doğal afet ulaşım engeli", "dogal afet ulasim engeli",
        "raporlu olduğu gün sınava girerse", "raporlu oldugu gun sinava girerse",
    ],
    "ders_kayit": [
        "ders kayıt tarihleri akademik takvim", "ders kayit tarihleri akademik takvim",
        "çap öğrencisi kredi", "cap ogrencisi kredi",
        "yan dal öğrencisi kredi", "yan dal ogrencisi kredi", "yandal öğrencisi kredi",
        "iki dönem üst üste agno 2.00 altı", "iki donem ust uste agno 2.00 alti",
        "üstten ders alamaz", "ustten ders alamaz",
        "kontenjan artırma", "kontenjan artirma",
        "ders grubu açılabilir", "ders grubu acilabilir",
        "12 kişilik ders grubu", "12 kisilik ders grubu",
        "ingilizce programda türkçe ders", "ingilizce programda turkce ders",
        "fakülte yönetim kurulu kararıyla çakışan ders", "fakulte yonetim kurulu karariyla cakisan ders",
        "kapatılan ders yerine", "kapatilan ders yerine",
    ],
    "diploma_bilgileri": [
        "ön lisans diploması", "on lisans diplomasi",
        "doktora diploması", "doktora diplomasi",
        "diploma ön yüz", "diploma on yuz",
        "kimlik bilgileri", "uyruk", "doğum yeri", "dogum yeri",
        "diploma boyutu", "diploma ölçüsü", "diploma olcusu",
    ],
    "diploma_teslim_kayip_ikinci_nusha": [
        "2005 sonrası kayıp diploma", "2005 sonrasi kayip diploma",
        "ikinci nüsha diploma", "ikinci nusha diploma",
        "gazete ilanı", "gazete ilani",
    ],
    "diploma_mezuniyet_tarihleri": [
        "obs yoksis", "obs yöksis", "yöksis", "yoksis",
        "mezuniyet kararı sonrası", "mezuniyet karari sonrasi",
        "öğrenci işleri daire başkanlığı", "ogrenci isleri daire baskanligi",
    ],
    "sinav_yonergesi": [
        "sınav türleri", "sinav turleri",
        "yazılı test sözlü elektronik", "yazili test sozlu elektronik",
        "ilk yirmi dakika", "ilk 20 dakika",
        "sınavdan çıkılamaz", "sinavdan cikilamaz",
        "sınav soruları dışarı çıkarılamaz", "sinav sorulari disari cikarilamaz",
        "final sınavları iki hafta", "final sinavlari iki hafta",
    ],
    "sinav_itiraz": [
        "itiraz fakülte dekanlığına", "itiraz fakulte dekanligina",
        "yüksekokul müdürlüğüne dilekçe", "yuksekokul mudurlugune dilekce",
        "maddi hata yoksa not değişmez", "maddi hata yoksa not degismez",
        "not değişikliği yönetim kurulu kararı", "not degisikligi yonetim kurulu karari",
        "üç kişilik komisyon", "uc kisilik komisyon",
        "bütünleme sınavından önce üç iş günü", "butunleme sinavindan once uc is gunu",
    ],
    "yaz_okulu": [
        "başka üniversite öğrencisi ytü yaz okulu", "baska universite ogrencisi ytu yaz okulu",
        "ytü yaz okulunda dış öğrenci", "ytu yaz okulunda dis ogrenci",
        "yaz okulunda en fazla 9 kredi", "yaz okulunda dokuz kredi",
    ],
    "ozel_ogrenci_ytuden_giden": [
        "ytü öğrencisi başka üniversiteden özel öğrenci", "ytu ogrencisi baska universiteden ozel ogrenci",
        "ytü öğrencisi başka üniversiteden ders alırsa", "ytu ogrencisi baska universiteden ders alirsa",
        "diğer yükseköğretim kurumunda özel öğrenci", "diger yuksekogretim kurumunda ozel ogrenci",
        "toplam alınabilecek yerel kredi", "toplam alinabilecek yerel kredi",
        "öğrencilik hakları ytü'de devam eder", "ogrencilik haklari ytude devam eder",
        "ders içerik yerel kredi akts", "ders icerik yerel kredi akts",
    ],
    "ozel_ogrenci_ytuye_gelen": [
        "başka üniversite öğrencisi ytü yaz okulunda", "baska universite ogrencisi ytu yaz okulunda",
        "ytüden ders almak isteyen dış öğrenci", "ytuden ders almak isteyen dis ogrenci",
        "başka üniversite öğrencisi ytüden ders", "baska universite ogrencisi ytuden ders",
    ],
    "isletmede_mesleki_egitim_tanimlar": [
        "bölüm komisyonu kimlerden oluşur", "bolum komisyonu kimlerden olusur",
        "fakülte komisyonu kimlerden oluşur", "fakulte komisyonu kimlerden olusur",
        "eğitici personel tanımı", "egitici personel tanimi",
        "sorumlu öğretim elemanı tanımı", "sorumlu ogretim elemani tanimi",
    ],
    "isletmede_mesleki_egitim_komisyonlar_gorevler": [
        "bilgi bankasını kim günceller", "bilgi bankasini kim gunceller",
        "oryantasyonu kim düzenler", "oryantasyonu kim duzenler",
        "iyileştirme taleplerini kim değerlendirir", "iyilestirme taleplerini kim degerlendirir",
        "revizyon değişiklik talepleri", "revizyon degisiklik talepleri",
    ],
    "isletmede_mesleki_egitim_isletme_egitici_sorumlu_ogrenci": [
        "işletmedeki öğrenciden kim sorumlu", "isletmedeki ogrenciden kim sorumlu",
        "öğrencinin mesleki ve etik sorumluluğu", "ogrencinin mesleki ve etik sorumlulugu",
        "haftalık çalışma planını kim yapar", "haftalik calisma planini kim yapar",
    ],
    "isletmede_mesleki_egitim_basvuru_degerlendirme_itiraz": [
        "bir yarıyıl süre ile tam zamanlı", "bir yariyil sure ile tam zamanli",
        "tam zamanlı ve kesintisiz", "tam zamanli ve kesintisiz",
        "değerlendirme notunun yüzde kırkı", "degerlendirme notunun yuzde kirki",
        "eğitici personel yüzde altmış", "egitici personel yuzde altmis",
    ],
    "isletmede_mesleki_egitim_diger_hukumler": [
        "işletmede mesleki eğitim sırasında sigorta", "isletmede mesleki egitim sirasinda sigorta",
        "işletmede mesleki eğitim sırasında hastalık", "isletmede mesleki egitim sirasinda hastalik",
        "işletmede mesleki eğitim gece çalışması", "isletmede mesleki egitim gece calismasi",
    ],
}

for _category, _keywords in V8_EXTRA_KEYWORDS.items():
    if _category in CATEGORY_RULES:
        CATEGORY_RULES[_category].setdefault("keywords", [])
        for _keyword in _keywords:
            if _keyword not in CATEGORY_RULES[_category]["keywords"]:
                CATEGORY_RULES[_category]["keywords"].append(_keyword)

# ---------------------------------------------------------
# V12 EK ANAHTAR KELİMELER
# 200/296/300 testlerinde kaçan mikro hükümler ve alt kategori ayrımları.
# ---------------------------------------------------------
V12_EXTRA_KEYWORDS = {
    "staj": [
        "staj yapılacak işyerinin uygunluğu", "staj yapilacak isyerinin uygunlugu",
        "staj yerinin uygun olup olmadığı", "staj yerinin uygun olup olmadigi",
        "staj işyerini kim onaylar", "staj isyerini kim onaylar",
        "staj iki parçaya bölünebilir", "staj iki parcaya bolunebilir",
        "en fazla ikiye bölünebilir", "en fazla ikiye bolunebilir",
        "staj süresi 10 iş gününden az olmamak", "staj suresi 10 is gununden az olmamak",
        "staj çalışmasının en fazla 30 iş günü", "staj calismasinin en fazla 30 is gunu",
        "yükseköğretim kurumlarının laboratuvarlarında", "yuksekogretim kurumlarinin laboratuvarlarinda",
        "staj defteri", "staj sicil ve değerlendirme formu", "staj sicil ve degerlendirme formu",
        "sigorta girişi yapılmadan staja başlanamaz", "sigorta girisi yapilmadan staja baslanamaz",
        "dersinin veya sınavının olduğu günlerde staj yapamaz", "dersinin veya sinavinin oldugu gunlerde staj yapamaz",
        "resmi tatil günlerinde yapılan çalışmalar staj süresi olarak kabul edilmez", "resmi tatil gunlerinde yapilan calismalar staj suresi olarak kabul edilmez",
        "erasmus en az 60 iş günü", "erasmus en az 60 is gunu",
        "isteğe bağlı staj en fazla iki kez", "istege bagli staj en fazla iki kez",
    ],
    "sinav_yonergesi": [
        "kısa sınav önceden bildirilir", "kisa sinav onceden bildirilir",
        "quiz önceden duyurulur", "quiz onceden duyurulur",
        "sınavın ilk 20 dakikasında çıkılamaz", "sinavin ilk 20 dakikasinda cikilamaz",
        "ilk yirmi dakika sınavdan çıkılamaz", "ilk yirmi dakika sinavdan cikilamaz",
        "son iki öğrenci", "son iki ogrenci",
        "son iki öğrenci birlikte çıkar", "son iki ogrenci birlikte cikar",
        "soru kağıdı dışarı çıkarılamaz", "soru kagidi disari cikarilamaz",
        "cevap kağıdı dışarı çıkarılamaz", "cevap kagidi disari cikarilamaz",
        "yarıyıl sonu sınav sonuçları iki hafta", "yariyil sonu sinav sonuclari iki hafta",
        "akıllı saat", "akilli saat", "cep telefonu", "elektronik cihaz",
    ],
    "onceki_ogrenme": [
        "başvurular bölüm başkanlığına yapılır", "basvurular bolum baskanligina yapilir",
        "enstitülerde anabilim dalı başkanlığına", "enstitulerde anabilim dali baskanligina",
        "önceden kazanılmış yeterliliklerin tanınması komisyonu", "onceden kazanilmis yeterliliklerin taninmasi komisyonu",
        "komisyon iki yıl sürelidir", "komisyon iki yil surelidir",
        "başarısız dersler değerlendirilmez", "basarisiz dersler degerlendirilmez",
        "18 kredi", "on sekiz kredi",
        "40 saat 1 kredi", "50 saat", "yayınlar için istisna", "yayinlar icin istisna",
        "tanıma sonuçlarına itiraz", "tanima sonuclarina itiraz",
    ],
    "ozel_ogrenci_ytuye_gelen": [
        "zorunlu ingilizce hazırlık sınıfına özel öğrenci kabul edilmez", "zorunlu ingilizce hazirlik sinifina ozel ogrenci kabul edilmez",
        "en az bir yarıyılı tamamlamış", "en az bir yariyili tamamlamis",
        "4.0 üzerinden en az 3.0", "100 üzerinden en az 80",
        "yaz okulunda bu koşul aranmaz", "yaz okulunda bu kosul aranmaz",
        "üniversitemizden bir yarıyılda en fazla 25 kredilik", "universitemizden bir yariyilda en fazla 25 kredilik",
        "özel öğrenci haklardan yararlanamaz", "ozel ogrenci haklardan yararlanamaz",
        "katkı payını kayıtlı olduğu yükseköğretim kurumuna öder", "katki payini kayitli oldugu yuksekogretim kurumuna oder",
    ],
    "ozel_ogrenci_ytuden_giden": [
        "senatosunca onaylanmış üniversite ve bölümler", "senatosunca onaylanmis universite ve bolumler",
        "dersin haftalık ders programı", "dersin haftalik ders programi",
        "içerik yerel kredi akts bilgilerini gösterir onaylı belge", "icerik yerel kredi akts bilgilerini gosterir onayli belge",
        "aynı anda hem üniversitemizden hem de diğer yükseköğretim kurumlarından", "ayni anda hem universitemizden hem de diger yuksekogretim kurumlarindan",
        "özel öğrencilikte geçirdiği süre öğretim süresine dahildir", "ozel ogrencilikte gecirdigi sure ogretim suresine dahildir",
    ],
    "ders_kayit": [
        "dersin kontenjanını sadece o dersi açan bölüm program başkanlığı arttırabilir",
        "dersin kontenjanini sadece o dersi acan bolum program baskanligi arttirabilir",
        "bir ders grubunun açılabilmesi için gruba kayıtlı öğrenci sayısı en az 15", "bir ders grubunun acilabilmesi icin gruba kayitli ogrenci sayisi en az 15",
        "bu sayı 10 kişiye kadar düşürülebilir", "bu sayi 10 kisiye kadar dusurulebilir",
        "Çift Anadal Yan Dal Pedagojik Formasyon 31 kredi", "Cift Anadal Yan Dal Pedagojik Formasyon 31 kredi",
        "iki yarıyıl üst üste agno 2.00 altında", "iki yariyil ust uste agno 2.00 altinda",
        "yabancı dilde öğretim yapılan programlarda kayıtlı öğrenciler Türkçe verilen derslere kayıt yaptıramaz",
        "yabanci dilde ogretim yapilan programlarda kayitli ogrenciler Turkce verilen derslere kayit yaptiramaz",
        "atatürk ilkeleri ve inkılap tarihi ile türk dili hariç", "ataturk ilkeleri ve inkilap tarihi ile turk dili haric",
    ],
    "diploma_bilgileri": [
        "diplomanın ön yüzünde", "diplomanin on yuzunde",
        "diploma numarası", "diploma numarasi",
        "t.c. kimlik numarası", "tc kimlik numarasi",
        "diploma derecesi veya unvan", "mezun olunan birim adı", "mezun olunan birim adi",
        "ikinci öğretim ibaresi yer almaz", "ikinci ogretim ibaresi yer almaz",
        "çift anadal ibaresi yer almaz", "cift anadal ibaresi yer almaz",
        "365mm x 280mm", "232mm x 317mm",
    ],
    "diploma_mezuniyet_tarihleri": [
        "tezsiz yüksek lisans mezuniyet tarihi", "tezsiz yuksek lisans mezuniyet tarihi",
        "ilgili enstitü yönetim kurulu toplantı tarihi", "ilgili enstitu yonetim kurulu toplanti tarihi",
        "tezli lisansüstü mezuniyet tarihi", "tezli lisansustu mezuniyet tarihi",
        "imzalı nihai nüsha enstitüye teslim", "imzali nihai nusha enstituye teslim",
    ],
    "diploma_eki_yandal_belgeler": [
        "yandal programını en az 2.5 ortalamayla tamamlayan", "yandal programini en az 2.5 ortalamayla tamamlayan",
        "anadal programında mezuniyet hakkını elde eden", "anadal programinda mezuniyet hakkini elde eden",
        "diploma eki ingilizce", "diploma eki İngilizce",
    ],
    "diploma_teslim_kayip_ikinci_nusha": [
        "diploma hazırlama süresi 25 iş günü", "diploma hazirlama suresi 25 is gunu",
        "noter vekâletnamesi", "noter vekaletnamesi",
        "posta yolu ile veya e-posta ile gönderilmez", "posta yolu ile veya e-posta ile gonderilmez",
        "gazete ilanı", "gazete ilani",
    ],
    "lisansustu_doktora": [
        "en geç beşinci yarıyılın sonuna kadar yeterlik", "en gec besinci yariyilin sonuna kadar yeterlik",
        "en geç yedinci yarıyılın sonuna kadar yeterlik", "en gec yedinci yariyilin sonuna kadar yeterlik",
        "doktora ders başarı notu", "doktora ders basari notu",
        "cb doktora için başarısız", "cb doktora icin basarisiz",
        "doktora programları ikinci öğretim olarak açılamaz", "doktora programlari ikinci ogretim olarak acilamaz",
        "tez izleme komitesi", "tez önerisi", "tez onerisi",
    ],
    "lisansustu_tezli_yuksek_lisans": [
        "tez ve uzmanlık alan derslerine kayıt yaptırmak zorundadır", "tez ve uzmanlik alan derslerine kayit yaptirmak zorundadir",
        "en az 120 akts", "bir eğitim öğretim dönemi 60 akts", "bir egitim ogretim donemi 60 akts",
        "diğer yükseköğretim kurumlarında verilmekte olan derslerden en fazla iki ders", "diger yuksekogretim kurumlarinda verilmekte olan derslerden en fazla iki ders",
    ],
    "lisansustu_bilimsel_hazirlik_kayit_ogretim": [
        "bilimsel hazırlık programının süresi en çok iki yarıyıldır", "bilimsel hazirlik programinin suresi en cok iki yariyildir",
        "yaz öğretimi bu süreye dahil edilmez", "yaz ogretimi bu sureye dahil edilmez",
        "programda geçirilen süre yüksek lisans veya doktora programı sürelerine dahil edilmez",
        "programda gecirilen sure yuksek lisans veya doktora programi surelerine dahil edilmez",
        "lisansüstü programlardaki dersler not sistemine göre değerlendirilir", "lisansustu programlardaki dersler not sistemine gore degerlendirilir",
    ],
    "lisansustu_kontenjan_danismanlik_ek_sure": [
        "tez savunması ek süre", "tez savunmasi ek sure",
        "afet salgın tez aşaması ek süre", "afet salgin tez asamasi ek sure",
        "danışmanlık kontenjanı", "danismanlik kontenjani",
    ],
    "kurumlar_arasi_yatay_gecis": [
        "genel not ortalamasının dörtlük not sisteminde en az 3.0", "genel not ortalamasinin dortluk not sisteminde en az 3.0",
        "yüzlük not sisteminde en az 75", "yuzluk not sisteminde en az 75",
        "başarı şartını sağlayamayan ancak merkezi yerleştirme puanı", "basari sartini saglayamayan ancak merkezi yerlestirme puani",
        "boş kalan kontenjan olması halinde değerlendirilir", "bos kalan kontenjan olmasi halinde degerlendirilir",
        "ikinci öğretimde kayıtlı öğrenciler başvuramaz", "ikinci ogretimde kayitli ogrenciler basvuramaz",
        "sınavsız ikinci üniversite başvurusunda bulunamaz", "sinavsiz ikinci universite basvurusunda bulunamaz",
    ],
    "merkezi_yerlestirme_yatay_gecis": [
        "hazırlık sınıfı ara sınıflar ve son sınıf dahil", "hazirlik sinifi ara siniflar ve son sinif dahil",
        "yalnızca bir defa yararlanabilir", "yalnizca bir defa yararlanabilir",
        "öSYM merkezi yerleştirme sonucu kayıt hakkı kazandıkları yükseköğretim kurumuna geri dönebilir",
        "osym merkezi yerlestirme sonucu kayit hakki kazandiklari yuksekogretim kurumuna geri donebilir",
        "bahar yarıyılı için başvuru kabul edilmez", "bahar yariyili icin basvuru kabul edilmez",
    ],
    "kurum_ici_yatay_gecis": [
        "öğreniminin üçüncü veya beşinci yarıyılının başında", "ogreniminin ucuncu veya besinci yariyilinin basinda",
        "sadece bir program için kurum içi yatay geçiş", "sadece bir program icin kurum ici yatay gecis",
        "her dersin not karşılığının 4.0 üzerinden en az 2.0", "her dersin not karsiliginin 4.0 uzerinden en az 2.0",
    ],
    "cap": [
        "yalnız bir program için çift anadal başvurusunda bulunabilir", "yalniz bir program icin cift anadal basvurusunda bulunabilir",
        "çap hakkı kazanan bir daha çap başvurusunda bulunamaz", "cap hakki kazanan bir daha cap basvurusunda bulunamaz",
        "başvurular sadece güz yarıyılında yapılır", "basvurular sadece guz yariyilinda yapilir",
        "agno en az 2.72", "ilk yüzde 20", "ilk yuzde 20",
    ],
    "yandal": [
        "yan dal programına en erken üçüncü en geç altıncı yarıyıl", "yan dal programina en erken ucuncu en gec altinci yariyil",
        "aynı anda en fazla iki yan dal programına başvurabilir", "ayni anda en fazla iki yan dal programina basvurabilir",
        "anadal programındaki agno en az 2.5", "anadal programindaki agno en az 2.5",
        "yan dal programında en az 5 en çok 10 ders", "yan dal programinda en az 5 en cok 10 ders",
    ],
    "yaz_okulu": [
        "yaz okulu süresi en az 5 hafta final sınav süresi bir hafta", "yaz okulu suresi en az 5 hafta final sinav suresi bir hafta",
        "günlük toplam ders saati 6 ders saatini geçemez", "gunluk toplam ders saati 6 ders saatini gecemez",
        "normal yarıyılda yapılan toplam ders saati kadardır", "normal yariyilda yapilan toplam ders saati kadardir",
        "uzaktan eğitim modülü onlinekampus", "uzaktan egitim modulu onlinekampus",
        "başka yükseköğretim kurumlarında okuyan öğrencilere", "baska yuksekogretim kurumlarinda okuyan ogrencilere",
    ],
    "sinav_itiraz": [
        "ilan edilmesinin veya akademik takvimde belirtilen sınav not girişlerinin son gününden itibaren üç iş günü",
        "ilan edilmesinin veya akademik takvimde belirtilen sinav not girislerinin son gununden itibaren uc is gunu",
        "itiraz dilekçesinin alındığı tarihten itibaren en geç 10 iş günü", "itiraz dilekcesinin alindigi tarihten itibaren en gec 10 is gunu",
        "final sonuçlarına itirazlar bütünleme sınavından 3 iş günü öncesinden", "final sonuclarina itirazlar butunleme sinavindan 3 is gunu oncesinden",
    ],
    "bitirme_calismasi": [
        "sınav herkese açıktır", "sinav herkese aciktir",
        "bitirme çalışmasının başarı değerlendirmesi çalışma ve sözlü sınav", "bitirme calismasinin basari degerlendirmesi calisma ve sozlu sinav",
        "bitirme çalışması yaz okulunda yapılmaz", "bitirme calismasi yaz okulunda yapilmaz",
    ],
}

for _category, _keywords in V12_EXTRA_KEYWORDS.items():
    if _category in CATEGORY_RULES:
        CATEGORY_RULES[_category].setdefault("keywords", [])
        for _keyword in _keywords:
            if _keyword not in CATEGORY_RULES[_category]["keywords"]:
                CATEGORY_RULES[_category]["keywords"].append(_keyword)




# -------------------------------------------------------------------------
# Ek kategori anahtar kelimeleri
# Amaç: v12 testlerinde zayıf kalan mikro madde, belge, süre ve alt kategori
# sorularını daha güçlü yakalamak. Bu liste kaynak üretmez; yalnızca doğru
# kategoriye yönlendirme / retrieval sinyali olarak kullanılır.
# -------------------------------------------------------------------------
EXTRA_KEYWORDS = {
    "staj": [
        "staj en az 20 iş günü", "staj en az 20 is gunu",
        "staj en fazla ikiye bölünebilir", "staj en fazla ikiye bolunebilir",
        "her parça en az 10 iş günü", "her parca en az 10 is gunu",
        "yükseköğretim kurumlarının laboratuvarlarında en fazla 30 iş günü",
        "yuksekogretim kurumlarinin laboratuvarlarinda en fazla 30 is gunu",
        "staj defterinde düzeltme", "staj defterinde duzeltme",
        "stajı reddedilen öğrenci", "staji reddedilen ogrenci",
        "staj reddine itiraz bir hafta", "staj reddine itiraz 1 hafta",
        "staj sicil ve değerlendirme formu", "staj sicil ve degerlendirme formu",
        "staj ücretleri işsizlik fonu katkısı", "staj ucretleri issizlik fonu katkisi",
    ],
    "yandal": [
        "aynı anda en fazla iki yan dal", "ayni anda en fazla iki yan dal",
        "yan dal başvurusu üçüncü altıncı yarıyıl", "yan dal basvurusu ucuncu altinci yariyil",
        "her dersten en az 2.0", "her dersin not karşılığı en az 2.0",
        "dgs ile gelen yan dal başvuramaz", "dgs ile gelen yandal basvuramaz",
        "yan dal kaydı askıya alınır", "yan dal kaydi askiya alinir",
        "anadal ile ortak dersler için yeni dersler belirlenir",
        "anadal ile ortak dersler icin yeni dersler belirlenir",
    ],
    "cap": [
        "çap tüm derslerden başarılı", "cap tum derslerden basarili",
        "çap her ders en az 2.0", "cap her ders en az 2.0",
        "agno 2.72 altında merkezi yerleştirme puanı", "agno 2.72 altinda merkezi yerlestirme puani",
        "yüzde otuzdan yüzde yüze iys aranmaz", "yuzde otuzdan yuzde yuze iys aranmaz",
        "çap hakkı kazanıp kayıt yaptıran tekrar başvuramaz",
        "cap hakki kazanip kayit yaptiran tekrar basvuramaz",
    ],
    "kurum_ici_yatay_gecis": [
        "kurum içi yatay geçiş sadece bir program", "kurum ici yatay gecis sadece bir program",
        "kurum içi tüm derslerden en az 2.0", "kurum ici tum derslerden en az 2.0",
        "kurum içi agno en az 3.0", "kurum ici agno en az 3.0",
    ],
    "kurumlar_arasi_yatay_gecis": [
        "başarı şartını sağlayamayan boş kontenjan", "basari sartini saglayamayan bos kontenjan",
        "ikinci öğretim programlarına öğrenci alımı olmadığından başvuramaz",
        "ikinci ogretim programlarina ogrenci alimi olmadigindan basvuramaz",
        "dgs dahil merkezi yerleştirme dışı başvuramaz", "dgs dahil merkezi yerlestirme disi basvuramaz",
    ],
    "merkezi_yerlestirme_yatay_gecis": [
        "merkezi yerleştirme sadece bir defa", "merkezi yerlestirme sadece bir defa",
        "bahar yarıyılı için başvuru kabul edilmez", "bahar yariyili icin basvuru kabul edilmez",
        "başarı şartı aranmaz", "basari sarti aranmaz",
        "eski kurumuna geri dönebilir", "eski kurumuna geri donebilir",
    ],
    "ozel_ogrenci_ytuye_gelen": [
        "ytüye gelen özel öğrenci agno 3.00", "ytuye gelen ozel ogrenci agno 3.00",
        "100 üzerinden en az 80", "100 uzerinden en az 80",
        "yaz okulunda agno şartı aranmaz", "yaz okulunda agno sarti aranmaz",
        "hazırlık sınıfına özel öğrenci kabul edilmez", "hazirlik sinifina ozel ogrenci kabul edilmez",
        "özel öğrenci katkı payını kayıtlı olduğu kuruma öder", "ozel ogrenci katki payini kayitli oldugu kuruma oder",
        "dış öğrenci başvuru formu kimlik öğrenci belgesi transkript dekont",
        "dis ogrenci basvuru formu kimlik ogrenci belgesi transkript dekont",
    ],
    "ozel_ogrenci_ytuden_giden": [
        "senato tarafından onaylanan üniversite", "senato tarafindan onaylanan universite",
        "ytü öğrencisi başka üniversiteden ders alırsa öğrencilik hakları devam eder",
        "ytu ogrencisi baska universiteden ders alirsa ogrencilik haklari devam eder",
        "öğrenim boyunca en fazla 30 yerel kredi", "ogrenim boyunca en fazla 30 yerel kredi",
        "haftalık ders programı içerik yerel kredi akts", "haftalik ders programi icerik yerel kredi akts",
        "toplam 25 kredi agno 3.00 ise 28 kredi", "toplam 25 kredi agno 3.00 ise 28 kredi",
    ],
    "onceki_ogrenme": [
        "başvuru akademik takvimde belirtilen tarihler", "basvuru akademik takvimde belirtilen tarihler",
        "fotokopi faks onaysız belge işleme alınmaz", "fotokopi faks onaysiz belge isleme alinmaz",
        "komisyon iki yıl görev yapar", "komisyon iki yil gorev yapar",
        "ders koordinatörü önerisi komisyon raporu yönetim kurulu", "ders koordinatoru onerisi komisyon raporu yonetim kurulu",
        "laboratuvar atölye tez bitirme tasarım proje kabul edilmez",
        "laboratuvar atolye tez bitirme tasarim proje kabul edilmez",
        "tanınma sonucuna itiraz üç iş günü", "taninma sonucuna itiraz uc is gunu",
        "başarısız dersler önceki öğrenme kapsamında değerlendirilmez",
        "basarisiz dersler onceki ogrenme kapsaminda degerlendirilmez",
        "40 saat hizmet içi eğitim 1 kredi", "40 saat hizmet ici egitim 1 kredi",
        "pratik çalışma 50 saat 1 kredi", "pratik calisma 50 saat 1 kredi",
    ],
    "esdegerlik_intibak": [
        "agno hazırlık sınıfı hariç ağırlıklı genel not ortalaması",
        "agno hazirlik sinifi haric agirlikli genel not ortalamasi",
        "değişim programı protokol çerçevesinde", "degisim programi protokol cercevesinde",
        "not çizelgesi başarı durum belgesi", "not cizelgesi basari durum belgesi",
        "uzaktan eğitim programları hariç", "uzaktan egitim programlari haric",
    ],
    "sinav_yonergesi": [
        "sınavlar yazılı test sözlü elektronik", "sinavlar yazili test sozlu elektronik",
        "başarı notu kriterleri bologna bilgi sistemi", "basari notu kriterleri bologna bilgi sistemi",
        "devamsız öğrenciler yarıyıl sonu sınavına giremez",
        "devamsiz ogrenciler yariyil sonu sinavina giremez",
        "yarıyıl sonu sınav sonuçları iki hafta içinde", "yariyil sonu sinav sonuclari iki hafta icinde",
        "kısa sınav bir hafta önceden duyurulur", "kisa sinav bir hafta onceden duyurulur",
    ],
    "isletmede_mesleki_egitim_komisyonlar_gorevler": [
        "ime bilgi bankası koordinatörlük", "ime bilgi bankasi koordinatorluk",
        "oryantasyon eğitimi koordinatörlük", "oryantasyon egitimi koordinatorluk",
        "revizyon değişiklik iyileştirme talepleri koordinatörlük rektörlük",
        "revizyon degisiklik iyilestirme talepleri koordinatorluk rektorluk",
    ],
    "isletmede_mesleki_egitim_tanimlar": [
        "bölüm komisyonu kimlerden oluşur", "bolum komisyonu kimlerden olusur",
        "fakülte komisyonu kimlerden oluşur", "fakulte komisyonu kimlerden olusur",
    ],
    "isletmede_mesleki_egitim_isletme_egitici_sorumlu_ogrenci": [
        "işletmedeki öğrenciden eğitici personel sorumludur",
        "isletmedeki ogrenciden egitici personel sorumludur",
        "haftalık veya aylık çalışma raporu", "haftalik veya aylik calisma raporu",
    ],
    "isletmede_mesleki_egitim_basvuru_degerlendirme_itiraz": [
        "ime bir yarıyıl tam zamanlı kesintisiz", "ime bir yariyil tam zamanli kesintisiz",
        "fakülte komisyonu önerisi dekan onayı işletme",
        "fakulte komisyonu onerisi dekan onayi isletme",
    ],
    "ders_kayit": [
        "normal dönemde en fazla 25 yerel kredi", "normal donemde en fazla 25 yerel kredi",
        "çap yan dal pedagojik formasyon 31 kredi", "cap yan dal pedagojik formasyon 31 kredi",
        "iki yarıyıl üst üste agno 2.00 altında üst yarıyıl dersi alamaz",
        "iki yariyil ust uste agno 2.00 altinda ust yariyil dersi alamaz",
        "ders kontenjanını sadece dersi açan bölüm program başkanlığı artırır",
        "ders kontenjanini sadece dersi acan bolum program baskanligi artirir",
    ],
    "yaz_okulu": [
        "uzaktan eğitim modülü onlinekampus", "uzaktan egitim modulu onlinekampus",
        "uzaktan dersler senkron yürütülür", "uzaktan dersler senkron yurutulur",
        "başka üniversite öğrencisi özel öğrenci 9 kredi", "baska universite ogrencisi ozel ogrenci 9 kredi",
    ],
}

for _category, _keywords in EXTRA_KEYWORDS.items():
    if _category in CATEGORY_RULES:
        CATEGORY_RULES[_category].setdefault("keywords", [])
        for _keyword in _keywords:
            if _keyword not in CATEGORY_RULES[_category]["keywords"]:
                CATEGORY_RULES[_category]["keywords"].append(_keyword)
